### ISSUE TITLE
Blog post: Keep certificates stored in the SAF keyrings

### ISSUE THREAD

**Issue by chrisblumOMP** [openmainframeproject/foundation#128]
Zowe now supports the possibility to keep the certificates for communication safely stored within a SAF keyring. Here is how …

Posted by Jakub Balhar @Broadcom

@Joe-Winchester and @PeterFandelAtRocket
Please review and provide feedback.

**Comment by Joe-Winchester** [comment]
I've made some changes to https://medium.com/@jakub_43881/8cad4efd1b90 - added the {Core} to the first para (and not the title), qualified a few acronyms and added some more dates and links (in case someone is reading it in a few month's time as it did refer to "the latest Zowe release" without calling it out as 1.15 and saying where it could be obtained from.

Otherwise all good from me and this is a great article - looking forward to seeing it published and getting this great info in front of the Zowe community.
